# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 1026)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browse_sample_path_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_sample_path_button.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.browse_sample_path_button.setObjectName("browse_sample_path_button")
        self.sample_path_label = QtWidgets.QLabel(self.centralwidget)
        self.sample_path_label.setGeometry(QtCore.QRect(140, 10, 641, 31))
        self.sample_path_label.setFrameShape(QtWidgets.QFrame.Box)
        self.sample_path_label.setObjectName("sample_path_label")
        self.tree_sample_dir = QtWidgets.QTreeView(self.centralwidget)
        self.tree_sample_dir.setGeometry(QtCore.QRect(20, 50, 421, 331))
        self.tree_sample_dir.setObjectName("tree_sample_dir")
        self.listView_sample = QtWidgets.QListView(self.centralwidget)
        self.listView_sample.setGeometry(QtCore.QRect(450, 50, 331, 331))
        self.listView_sample.setDragEnabled(True)
        self.listView_sample.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listView_sample.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listView_sample.setObjectName("listView_sample")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(790, 10, 251, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_channel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_channel.setAutoFillBackground(False)
        self.label_channel.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_channel.setObjectName("label_channel")
        self.verticalLayout.addWidget(self.label_channel)
        self.label_bytepersample = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_bytepersample.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_bytepersample.setObjectName("label_bytepersample")
        self.verticalLayout.addWidget(self.label_bytepersample)
        self.label_samplerate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_samplerate.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_samplerate.setObjectName("label_samplerate")
        self.verticalLayout.addWidget(self.label_samplerate)
        self.label_duration = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_duration.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_duration.setObjectName("label_duration")
        self.verticalLayout.addWidget(self.label_duration)
        self.tree_library_dir = QtWidgets.QTreeView(self.centralwidget)
        self.tree_library_dir.setGeometry(QtCore.QRect(20, 590, 421, 401))
        self.tree_library_dir.setObjectName("tree_library_dir")
        self.browse_library_path_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_library_path_button.setGeometry(QtCore.QRect(20, 550, 111, 31))
        self.browse_library_path_button.setObjectName("browse_library_path_button")
        self.library_path_label = QtWidgets.QLabel(self.centralwidget)
        self.library_path_label.setGeometry(QtCore.QRect(140, 550, 641, 31))
        self.library_path_label.setFrameShape(QtWidgets.QFrame.Box)
        self.library_path_label.setObjectName("library_path_label")
        self.listView_library = QtWidgets.QListView(self.centralwidget)
        self.listView_library.setGeometry(QtCore.QRect(450, 590, 331, 401))
        self.listView_library.setDragEnabled(True)
        self.listView_library.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listView_library.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listView_library.setObjectName("listView_library")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(790, 790, 160, 128))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openfoxdot_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.openfoxdot_button.setObjectName("openfoxdot_button")
        self.verticalLayout_2.addWidget(self.openfoxdot_button)
        self.open_dir_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open_dir_button.setObjectName("open_dir_button")
        self.verticalLayout_2.addWidget(self.open_dir_button)
        self.open_source_dir_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open_source_dir_pushButton.setObjectName("open_source_dir_pushButton")
        self.verticalLayout_2.addWidget(self.open_source_dir_pushButton)
        self.swap_dir_name_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.swap_dir_name_Button.setObjectName("swap_dir_name_Button")
        self.verticalLayout_2.addWidget(self.swap_dir_name_Button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(790, 240, 160, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.reindex_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.reindex_button.setObjectName("reindex_button")
        self.verticalLayout_3.addWidget(self.reindex_button)
        self.rename_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rename_button.setObjectName("rename_button")
        self.verticalLayout_3.addWidget(self.rename_button)
        self.delete_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.delete_button.setCheckable(False)
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout_3.addWidget(self.delete_button)
        self.convert_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.convert_button.setObjectName("convert_button")
        self.verticalLayout_3.addWidget(self.convert_button)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 440, 761, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sampleButton6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton6.setObjectName("sampleButton6")
        self.gridLayout.addWidget(self.sampleButton6, 1, 2, 1, 1)
        self.sampleButton7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton7.setObjectName("sampleButton7")
        self.gridLayout.addWidget(self.sampleButton7, 0, 3, 1, 1)
        self.sampleButton4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton4.setObjectName("sampleButton4")
        self.gridLayout.addWidget(self.sampleButton4, 1, 1, 1, 1)
        self.sampleButton10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton10.setObjectName("sampleButton10")
        self.gridLayout.addWidget(self.sampleButton10, 1, 4, 1, 1)
        self.sampleButton5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton5.setObjectName("sampleButton5")
        self.gridLayout.addWidget(self.sampleButton5, 0, 2, 1, 1)
        self.sampleButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton2.setObjectName("sampleButton2")
        self.gridLayout.addWidget(self.sampleButton2, 1, 0, 1, 1)
        self.sampleButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton1.setObjectName("sampleButton1")
        self.gridLayout.addWidget(self.sampleButton1, 0, 0, 1, 1)
        self.sampleButton9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton9.setObjectName("sampleButton9")
        self.gridLayout.addWidget(self.sampleButton9, 0, 4, 1, 1)
        self.sampleButton8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton8.setObjectName("sampleButton8")
        self.gridLayout.addWidget(self.sampleButton8, 1, 3, 1, 1)
        self.sampleButton3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sampleButton3.setObjectName("sampleButton3")
        self.gridLayout.addWidget(self.sampleButton3, 0, 1, 1, 1)
        self.bank = QtWidgets.QSpinBox(self.centralwidget)
        self.bank.setGeometry(QtCore.QRect(110, 390, 51, 31))
        self.bank.setMaximum(99)
        self.bank.setObjectName("bank")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 390, 91, 21))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 390, 121, 18))
        self.label_2.setObjectName("label_2")
        self.sample_description = QtWidgets.QLineEdit(self.centralwidget)
        self.sample_description.setGeometry(QtCore.QRect(450, 390, 331, 21))
        self.sample_description.setObjectName("sample_description")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(790, 550, 161, 101))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.volume_slider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.volume_slider.setMaximum(100)
        self.volume_slider.setProperty("value", 100)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setInvertedAppearance(False)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout.addWidget(self.volume_slider)
        self.Volume_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Volume_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Volume_label.setObjectName("Volume_label")
        self.horizontalLayout.addWidget(self.Volume_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.loop_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.loop_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loop_checkbox.setAutoFillBackground(False)
        self.loop_checkbox.setChecked(False)
        self.loop_checkbox.setObjectName("loop_checkbox")
        self.verticalLayout_4.addWidget(self.loop_checkbox)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 430, 1011, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setGeometry(QtCore.QRect(780, 10, 221, 91))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.button_text = QtWidgets.QLineEdit(self.groupBox)
        self.button_text.setGeometry(QtCore.QRect(0, 30, 21, 31))
        self.button_text.setMaxLength(2)
        self.button_text.setObjectName("button_text")
        self.assign_button = QtWidgets.QPushButton(self.groupBox)
        self.assign_button.setGeometry(QtCore.QRect(40, 60, 131, 27))
        self.assign_button.setObjectName("assign_button")
        self.button_selection = QtWidgets.QComboBox(self.groupBox)
        self.button_selection.setGeometry(QtCore.QRect(40, 30, 131, 28))
        self.button_selection.setObjectName("button_selection")
        self.checkBox_sample_window = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_sample_window.setGeometry(QtCore.QRect(790, 390, 221, 23))
        self.checkBox_sample_window.setChecked(True)
        self.checkBox_sample_window.setObjectName("checkBox_sample_window")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(790, 930, 161, 51))
        self.exit_button.setObjectName("exit_button")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(790, 660, 160, 101))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.copy_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.copy_button.setObjectName("copy_button")
        self.verticalLayout_5.addWidget(self.copy_button)
        self.moveto_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.moveto_button.setObjectName("moveto_button")
        self.verticalLayout_5.addWidget(self.moveto_button)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(790, 160, 251, 77))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Up_Button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.Up_Button.setEnabled(True)
        self.Up_Button.setSizeIncrement(QtCore.QSize(0, 0))
        self.Up_Button.setText("")
        self.Up_Button.setIconSize(QtCore.QSize(32, 32))
        self.Up_Button.setArrowType(QtCore.Qt.UpArrow)
        self.Up_Button.setObjectName("Up_Button")
        self.horizontalLayout_2.addWidget(self.Up_Button)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.Down_Button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.Down_Button.setIconSize(QtCore.QSize(32, 32))
        self.Down_Button.setAutoRaise(False)
        self.Down_Button.setArrowType(QtCore.Qt.DownArrow)
        self.Down_Button.setObjectName("Down_Button")
        self.horizontalLayout_2.addWidget(self.Down_Button)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.position_label = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.position_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.position_label.setAutoFillBackground(False)
        self.position_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.position_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.position_label.setLineWidth(0)
        self.position_label.setSmallDecimalPoint(False)
        self.position_label.setDigitCount(2)
        self.position_label.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.position_label.setProperty("value", 0.0)
        self.position_label.setProperty("intValue", 0)
        self.position_label.setObjectName("position_label")
        self.horizontalLayout_2.addWidget(self.position_label)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.swap_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.swap_Button.setObjectName("swap_Button")
        self.verticalLayout_6.addWidget(self.swap_Button)
        self.swap_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.swap_spinBox.setObjectName("swap_spinBox")
        self.verticalLayout_6.addWidget(self.swap_spinBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.frame_2.raise_()
        self.browse_sample_path_button.raise_()
        self.sample_path_label.raise_()
        self.tree_sample_dir.raise_()
        self.listView_sample.raise_()
        self.verticalLayoutWidget.raise_()
        self.tree_library_dir.raise_()
        self.browse_library_path_button.raise_()
        self.library_path_label.raise_()
        self.listView_library.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.gridLayoutWidget.raise_()
        self.bank.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.sample_description.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.checkBox_sample_window.raise_()
        self.exit_button.raise_()
        self.verticalLayoutWidget_5.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CrashServer Samples Manager"))
        self.browse_sample_path_button.setText(_translate("MainWindow", "FoxDot Samples"))
        self.sample_path_label.setText(_translate("MainWindow", "Sample directory"))
        self.label_channel.setText(_translate("MainWindow", "Audio channel : "))
        self.label_bytepersample.setText(_translate("MainWindow", "Sample width : "))
        self.label_samplerate.setText(_translate("MainWindow", "Frame rate : "))
        self.label_duration.setText(_translate("MainWindow", "Duration : "))
        self.browse_library_path_button.setText(_translate("MainWindow", "Samples Library"))
        self.library_path_label.setText(_translate("MainWindow", "Sample Library"))
        self.openfoxdot_button.setToolTip(_translate("MainWindow", "Open FoxDot with the custom snd directory"))
        self.openfoxdot_button.setText(_translate("MainWindow", "Open FoxDot"))
        self.open_dir_button.setToolTip(_translate("MainWindow", "Open the Snd directory"))
        self.open_dir_button.setText(_translate("MainWindow", "Open Snd Directory"))
        self.open_source_dir_pushButton.setText(_translate("MainWindow", "Open Src Directory"))
        self.swap_dir_name_Button.setText(_translate("MainWindow", "Swap Dir Names"))
        self.reindex_button.setText(_translate("MainWindow", "Re-index"))
        self.rename_button.setText(_translate("MainWindow", "Rename"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.convert_button.setText(_translate("MainWindow", "Convert to wav"))
        self.sampleButton6.setText(_translate("MainWindow", "T"))
        self.sampleButton7.setText(_translate("MainWindow", "-"))
        self.sampleButton4.setText(_translate("MainWindow", "O"))
        self.sampleButton10.setText(_translate("MainWindow", "#"))
        self.sampleButton5.setText(_translate("MainWindow", "t"))
        self.sampleButton2.setText(_translate("MainWindow", "X"))
        self.sampleButton1.setText(_translate("MainWindow", "x"))
        self.sampleButton9.setText(_translate("MainWindow", "~"))
        self.sampleButton8.setText(_translate("MainWindow", ":"))
        self.sampleButton3.setText(_translate("MainWindow", "o"))
        self.label.setText(_translate("MainWindow", "Select Bank :"))
        self.label_2.setText(_translate("MainWindow", "Sample Description :"))
        self.Volume_label.setText(_translate("MainWindow", "Volume"))
        self.loop_checkbox.setText(_translate("MainWindow", "Loop samples"))
        self.groupBox.setTitle(_translate("MainWindow", "ReAssign Button"))
        self.assign_button.setText(_translate("MainWindow", "Assign"))
        self.checkBox_sample_window.setText(_translate("MainWindow", "Show/Hide Samples Description"))
        self.exit_button.setText(_translate("MainWindow", "EXIT"))
        self.copy_button.setToolTip(_translate("MainWindow", "Copy selected sample to Snd dir"))
        self.copy_button.setText(_translate("MainWindow", "Copy to FoxDot"))
        self.moveto_button.setToolTip(_translate("MainWindow", "Move selected sample to Snd dir"))
        self.moveto_button.setText(_translate("MainWindow", "Move to FoxDot"))
        self.Down_Button.setText(_translate("MainWindow", "..."))
        self.swap_Button.setText(_translate("MainWindow", "Swap"))
